//Teste de requisições REST
@baseURL = http://localhost:4000

###
//GET - Lista todas as categorias
GET {{baseURL}}/categorias
Content-Type: application/json

###
//POST - Inclui uma nova categoria
POST {{baseURL}}/categorias
Content-Type: application/json

{
    "nome": "Doceria",
    "status": "ativo"
}